# FROM floryn90/hugo:ext-alpine
#
# RUN apk add git && \
#   git config --global --add safe.directory /src

# Use the official Node.js 14 image
FROM node:20-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Install the Node.js CLI globally
RUN npm install -g postcss postcss-cli autoprefixer

# Set the entry point of the container
CMD [""]

